from enum import Enum


class Tag_Types(Enum):
    KEYWORD = "keyword"
    SYMBOL = "symbol"
    INT_CONST = "integerConstant"
    STRING_CONST = "stringConstant"
    IDENTIFIER = "identifier"
    CLASS = "class"
    CLASS_VAR_DEC = "classVarDec"
    TYPE = "type"
    SUB_ROUTINE_DEC = "subroutineDec"
    PARAM_LIST = "parameterList"
    SUB_ROUTINE_BODY = "subroutineBody"
    VAR_DEC = "varDec"
    CLASS_NAME = "className"
    SUB_ROUTINE_NAME = "subroutineName"
    VAR_NAME = "varName"
    STATEMENTS = "statement*"
    STATEMENT = "statment"
    LET_STATEMENT = "letStatement"
    IF_STATEMENT = "ifStatement"
    WHILE_STATEMENT = "whileStatement"
    DO_STATEMENT = "doStatement"
    RETURN_STATEMENT = "ReturnStatement"
    EXPRESSION = "expression"
    TERM = "term"
    SUB_ROUTINE_CALL = "subroutineCall"
    EXPRESSION_LIST = "expressionList"
    OP = "op"
    UNARY_OP = "unaryOp"
    KEYWORD_CONST = "KeywordConstant"
